[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Testing
verbosity = 3

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
